@echo off
setlocal enabledelayedexpansion

echo ========================================
echo Android Build with Ali Cloud Mirror
echo ========================================
echo.

echo [1] Setting environment variables...
set "JAVA_HOME=D:\app\java\jdk-17"
set "ANDROID_SDK_ROOT=D:\app\android"
set "ANDROID_HOME=D:\app\android"
set "GRADLE_USER_HOME=%USERPROFILE%\.gradle"

echo JAVA_HOME: %JAVA_HOME%
echo ANDROID_SDK_ROOT: %ANDROID_SDK_ROOT%
echo GRADLE_USER_HOME: %GRADLE_USER_HOME%
echo.

echo [2] Checking Java...
"%JAVA_HOME%\bin\java" -version 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Java not working
    exit /b 1
)

echo.

echo [3] Preparing gradle wrapper with extended timeout...
(
echo #Auto-generated by build script
echo distributionBase=GRADLE_USER_HOME
echo distributionPath=wrapper/dists
echo distributionUrl=https://mirrors.aliyun.com/gradle/gradle-8.0-bin.zip
echo networkTimeout=60000
echo zipStoreBase=GRADLE_USER_HOME
echo zipStorePath=wrapper/dists
) > gradle\wrapper\gradle-wrapper.properties

echo [4] Creating init script for mirrors...
(
echo allprojects {
echo     repositories {
echo         maven { url 'https://maven.aliyun.com/repository/google' }
echo         maven { url 'https://maven.aliyun.com/repository/central' }
echo         maven { url 'https://maven.aliyun.com/repository/public' }
echo         maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
echo         google()
echo         mavenCentral()
echo         maven { url 'https://jitpack.io' }
echo     }
echo }
echo 
echo buildscript {
echo     repositories {
echo         maven { url 'https://maven.aliyun.com/repository/google' }
echo         maven { url 'https://maven.aliyun.com/repository/central' }
echo         maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
echo         google()
echo         mavenCentral()
echo     }
echo }
) > init.gradle

echo [5] Checking if gradle is already downloaded...
set "GRADLE_ZIP=%GRADLE_USER_HOME%\wrapper\dists\gradle-8.0-bin\gradle-8.0-bin.zip"
if exist "!GRADLE_ZIP!" (
    echo Gradle already downloaded
) else (
    echo Gradle not found. Downloading from mirror...
    echo This may take a few minutes...
    
    powershell -Command "Invoke-WebRequest -Uri 'https://mirrors.aliyun.com/gradle/gradle-8.0-bin.zip' -OutFile 'gradle-temp.zip' -TimeoutSec 300"
    if exist gradle-temp.zip (
        echo Download successful. Moving to gradle cache...
        if not exist "%GRADLE_USER_HOME%\wrapper\dists\gradle-8.0-bin" mkdir "%GRADLE_USER_HOME%\wrapper\dists\gradle-8.0-bin"
        move gradle-temp.zip "!GRADLE_ZIP!"
        echo Gradle downloaded and cached
    ) else (
        echo ERROR: Failed to download gradle
        exit /b 1
    )
)

echo.

echo [6] Building with mirror configuration...
echo This may take several minutes for first build...
echo.

set "GRADLE_OPTS=-Dorg.gradle.daemon=false -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000"
call gradlew.bat assembleDebug --init-script init.gradle --stacktrace --console=plain

if %errorlevel% neq 0 (
    echo.
    echo ERROR: Build failed. Trying without init script...
    
    echo [7] Trying alternative build approach...
    call gradlew.bat assembleDebug --stacktrace --console=plain
    
    if %errorlevel% neq 0 (
        echo.
        echo ========================================
        echo BUILD FAILED
        echo ========================================
        exit /b %errorlevel%
    )
)

echo.
echo ========================================
echo BUILD SUCCESSFUL!
echo ========================================
echo.
echo APK location: app\build\outputs\apk\debug\app-debug.apk
echo.

echo [8] Installing to Mate9 (if connected)...
where adb >nul 2>&1
if %errorlevel% equ 0 (
    adb devices | find "device" >nul 2>&1
    if %errorlevel% equ 0 (
        echo Device found. Installing APK...
        adb install -r app\build\outputs\apk\debug\app-debug.apk
        echo Installation complete!
    ) else (
        echo No Android device found. Connect Mate9 and enable USB debugging.
    )
) else (
    echo ADB not found. Skipping installation.
)

endlocal